name: Deploy the Product Page to GitHub Pages

env: # Change these to your preferences any image url can also be a base encoded image
  GITHUB_PAGES_BRANCH: gh-pages

  # options: "true" | "false"
  USE_GITHUB_REPOSITORY_NAME_AS_PATH_PREFIX: "true"
  
  GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
  API_BASE_URL: "https://api.gateway.commonground.nu/api"
  NL_DESIGN_THEME_CLASSNAME: "noordwijk-theme"
  DEV_ENVIRONMENT: "true"
  SHOW_CATEGORY: "true"
  SHOW_ORGANIZATION: "false"
  FAVICON_URL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAACXBIWXMAAA7EAAAOxAGVKw4bAAADcklEQVRYhcWXXUwUVxSAvzsMLOwCCwusW9lGakRUEoIWIaixxtYao9Rq4m9MrDFpbNr0ySbtw8akJk30ycc+tVYTE4naB4kPVdvQpm4sJjuiiH8LBETUUGDXuv+7tw9QWtiddYa49TxMMvf8fTlz7p17BEAgFN0CHAUahBAKORQpZQroBjx2q6VDTCW/KITIZd5MIABtIhCK+oQQjf9r9n8hNBEIRZO5LnsWgJSql/yS7zG3BicMB3u3vpIWRzdfXxvlwck/mazwpGz6oJHd+1en+QghFFUv4PhfMYbHwoaSO4oLaCrv4UzfE/quBrjfOzJDf+DQOl1fXYCW2grUPMGdR0HGX8R0A0gp2fZ2OXnJXn7xj9H/23iaTWNTja6/7rdf5Cph16oFbGhw6ToD1M0vpdnu4/uBJClNJRKOz9AvrHVSVm7T9detgBFRBOxYUUgsGeXn/mGedEbTbJY3vZU1hmGA0qJ8lrlLARBTD7fDSrV1mB/u5VF010YwMNm0LatrmfeGHYANmxteDYCrrJC9a2rS1hM42VK/mKvHTk2v7dzXSuvaxYbiGt7/kXiSSCyZUWcvtPHZ4Y0oivnT1DDA4GiIL89o/HRzJKN+RfNCDn663jSAqSZMSQjO6vL/yv6P30G7MWAKwPQRXKDquyiKwpFjO3BUFhuOZ6oCBarC2qXOrDaOimIcFcYBTFXg/QYXjvyxtPVb2qCZMHMDqCyx8F6dIP/5H2m69tNefu+8mzsAKSXbmt3YJi6RsNZl1B/96jxPR4z/PU0BLHPbaawaBRnDH7FntAkGwngOnyWRyHxWzBlAVQTbm91YxjoYKmjlpO+Kru1tbYhvT1w2BSCC4ZjMZhCNJ7FFfKihHj7X4hQlClkjZp7v7ae99HQPTb9/1/4JS+qrDQG8dBtaVAXLxGUeWrdy7s5xPnq+mSNn27P6vNptKASRig85fv1XttasovNib1bz6jcdOF2Z+2RuAECiaAkDE89w+asIh/RvRwDLV9YYTm4YQAjBhT0eFjidVFaV/HOn1wHIfgFJi/2yJpwtUkr6Hjyly+uny+tHuzFAOByb1v145Qtc88tyBzBb4vEEt28O0eX10//wGd+c2IOZKeu1DyYKk4Pi65JuBfBka6pcyVROj2K3WjqANimlNjU65zpxSkqpAW12q6XjbxkAOtY2FESlAAAAAElFTkSuQmCC"
  ORGANISATION_NAME: "Gemeente Noordwijk"
  JUMBOTRON_IMAGE_URL: "https://raw.githubusercontent.com/ConductionNL/woo-website-noordwijk/main/images/Bollenvelden%20Panorama%20Noordwijkerhout%20-%20Luchtfoto%5B3766%5D.JPG"
  FOOTER_LOGO_URL: "false"
  FOOTER_LOGO_HREF: "https://www.noordwijk.nl/"
  FOOTER_CONTENT: "https://raw.githubusercontent.com/ConductionNL/${{github.event.repository.name}}/main/FooterContent.json"
  FOOTER_CONTENT_HEADER: "heading-2"
  OIDN_NUMBER: "00000001825792150000"
  ENV_VARS_SET: "true"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get the WOO Website Template Code
        uses: actions/checkout@v2
        with:
          repository: ConductionNL/woo-website-template
          ref: development

      # With special thanxs to https://github.com/SpicyPizza/create-envfile
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_GITHUB_REPOSITORY_NAME: ${{ env.GITHUB_REPOSITORY_NAME }}
          envkey_USE_GITHUB_REPOSITORY_NAME_AS_PATH_PREFIX: ${{ env.USE_GITHUB_REPOSITORY_NAME_AS_PATH_PREFIX }}
          envkey_GATSBY_API_BASE_URL: ${{ env.API_BASE_URL }}
          envkey_GATSBY_NL_DESIGN_THEME_CLASSNAME: ${{ env.NL_DESIGN_THEME_CLASSNAME }}
          envkey_GATSBY_DEV_ENVIRONMENT: ${{ env.DEV_ENVIRONMENT }}
          envkey_GATSBY_SHOW_CATEGORY: ${{ env.SHOW_CATEGORY }}
          envkey_GATSBY_SHOW_ORGANIZATION: ${{ env.SHOW_ORGANIZATION }}
          envkey_GATSBY_FAVICON_URL: ${{ env.FAVICON_URL }}
          envkey_GATSBY_ORGANISATION_NAME: ${{ env.ORGANISATION_NAME }}
          envkey_GATSBY_JUMBOTRON_IMAGE_URL: ${{ env.JUMBOTRON_IMAGE_URL }}
          envkey_GATSBY_FOOTER_LOGO_URL: ${{ env.FOOTER_LOGO_URL }}
          envkey_GATSBY_FOOTER_LOGO_HREF: ${{ env.FOOTER_LOGO_HREF }}
          envkey_GATSBY_FOOTER_CONTENT: ${{ env.FOOTER_CONTENT }}
          envkey_GATSBY_FOOTER_CONTENT_HEADER: ${{ env.FOOTER_CONTENT_HEADER }}
          envkey_GATSBY_OIDN_NUMBER: ${{ env.OIDN_NUMBER }}
          envkey_GATSBY_ENV_VARS_SET: ${{ env.ENV_VARS_SET }}
          directory: pwa/static
          file_name: .env.production
          fail_on_empty: true
          sort_keys: false

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: cd pwa && npm install

      - name: Install parcel/watcher
        run: cd pwa && npm install @parcel/watcher

      - name: Remove old Gatsby cache
        run: rm -rf pwa/.cache

      - name: Build application
        run: cd pwa && npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: ${{ env.GITHUB_PAGES_BRANCH }}
          folder: pwa/public
